name: "Terraform"

on:
  workflow_dispatch:
    inputs:
      dbName:
        description: 'DB Name'
        required: true
      instanceType:
        description: 'Instance Type'
        required: true
      instanceVersion:
        description: 'Instance Version'
        required: true  
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          # terraform_version: 0.13.0:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init
      
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color -var="prefix=${{ github.event.inputs.dbName }}" -var="engineversion=${{ github.event.inputs.instanceVersion }}"  -var="enginetype=${{ github.event.inputs.instanceType }}"     

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false -var="prefix=${{ github.event.inputs.dbName }}" -var="engineversion=${{ github.event.inputs.instanceVersion }}"  -var="enginetype=${{ github.event.inputs.instanceType }}"     
        continue-on-error: true
        
      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Manual Approval
        id: approval
        run: |
          echo "This is a manual approval step."
          echo "Review the changes and decide whether to proceed."
          echo "To approve, set the APPROVE_TERRAFORM_APPLY environment variable to 'true' in the repository secrets."
          echo "To reject, set it to 'false'."
          exit 1
        if: ${{ env.APPROVE_TERRAFORM_APPLY == 'false' }}

      - name: Terraform Apply
        run: |
          if [[ ${{ env.APPROVE_TERRAFORM_APPLY }} == 'true' ]]; then
            terraform apply -auto-approve -input=false -var="prefix=${{ github.event.inputs.dbName }}" -var="engineversion=${{ github.event.inputs.instanceVersion }}"  -var="enginetype=${{ github.event.inputs.instanceType }}"
          else
            echo "Terraform apply is not approved. Skipping."
          fi
